# Generated by Django 3.1 on 2022-04-05 10:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import main.models.positions
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Preorder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('preorder_id', models.IntegerField(unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('sum_rub', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('sum_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('sum_btc', models.DecimalField(blank=True, decimal_places=12, max_digits=16, null=True)),
                ('buyer', models.CharField(blank=True, max_length=30, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('order_date', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('product_name', models.CharField(blank=True, max_length=100, null=True)),
                ('size', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('status', models.CharField(blank=True, choices=[('open', 'Open'), ('closed', 'Closed')], max_length=30, null=True)),
                ('status_text', models.CharField(blank=True, max_length=60, null=True)),
            ],
            options={
                'ordering': ['-created_at', 'buyer'],
            },
        ),
        migrations.CreateModel(
            name='PreorderStage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=60, null=True)),
                ('comment', models.CharField(blank=True, max_length=60, null=True)),
                ('preorder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stages', to='main.preorder')),
            ],
            options={
                'ordering': ['-status_date'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('r_id', models.CharField(blank=True, default=main.models.positions.get_random_id, max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('open', 'Open'), ('closed', 'Closed')], max_length=30, null=True)),
                ('sum_btc', models.DecimalField(blank=True, decimal_places=12, max_digits=16, null=True)),
                ('btc_total_comissions', models.DecimalField(blank=True, decimal_places=12, max_digits=16, null=True)),
                ('comment', models.TextField(blank=True, max_length=300, null=True)),
                ('preorder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='positions', to='main.preorder')),
            ],
            options={
                'ordering': ['-created_at', 'preorder_id'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('order_id', models.CharField(blank=True, max_length=50, null=True)),
                ('type', models.CharField(blank=True, choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=30, null=True)),
                ('status', models.CharField(blank=True, choices=[('Filled', 'Filled'), ('New', 'New'), ('Cancelled', 'Cancelled')], max_length=30, null=True)),
                ('text', models.TextField(blank=True, max_length=300, null=True)),
                ('sum_btc', models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True)),
                ('sum_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('btc_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('usd_rate', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='main.position')),
                ('preorder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='main.preorder')),
            ],
            options={
                'ordering': ['-created_at', 'preorder_id'],
            },
        ),
        migrations.CreateModel(
            name='HedgeLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('origin', models.TextField(blank=True, max_length=30, null=True)),
                ('status', models.CharField(blank=True, choices=[('success', 'Success'), ('error', 'Error')], max_length=30, null=True)),
                ('text', models.TextField(blank=True, max_length=300, null=True)),
                ('preorder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='main.preorder')),
            ],
            options={
                'ordering': ['-created_at', 'origin'],
            },
        ),
    ]
