# Generated by Django 3.1 on 2022-02-10 14:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Preorder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('preorder_id', models.IntegerField(unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('sum_rub', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sum_btc', models.DecimalField(blank=True, decimal_places=12, max_digits=16, null=True)),
                ('buyer', models.CharField(blank=True, max_length=30, null=True)),
                ('finishing_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(blank=True, choices=[('open', 'Open'), ('closed', 'Closed')], max_length=30, null=True)),
                ('btc_rate_in', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('btc_rate_out', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('btc_quantity', models.DecimalField(blank=True, decimal_places=12, max_digits=16, null=True)),
                ('btc_total_comissions', models.DecimalField(blank=True, decimal_places=12, max_digits=16, null=True)),
                ('comment', models.TextField(blank=True, max_length=300, null=True)),
                ('preorder_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations', to='main.preorder')),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(blank=True, max_length=30, null=True)),
                ('text', models.TextField(blank=True, max_length=300, null=True)),
                ('btc_quantity', models.DecimalField(blank=True, decimal_places=12, max_digits=16, null=True)),
                ('btc_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('position_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations', to='main.position')),
            ],
        ),
    ]
