# Generated by Django 3.1 on 2022-02-24 14:18

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('origin', models.TextField(blank=True, max_length=30, null=True)),
                ('status', models.CharField(blank=True, choices=[('success', 'Success'), ('error', 'Error')], max_length=30, null=True)),
                ('text', models.TextField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
