# Generated by Django 3.1 on 2022-02-25 10:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_requestlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('order_id', models.CharField(blank=True, max_length=50, null=True)),
                ('type', models.CharField(blank=True, choices=[('open', 'Open'), ('closed', 'Closed')], max_length=30, null=True)),
                ('text', models.TextField(blank=True, max_length=300, null=True)),
                ('btc_quantity', models.DecimalField(blank=True, decimal_places=12, max_digits=16, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('btc_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('usd_rate', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('preorder_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations', to='main.preorder')),
            ],
        ),
        migrations.AlterField(
            model_name='position',
            name='preorder_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='positions', to='main.preorder'),
        ),
        migrations.DeleteModel(
            name='Operation',
        ),
        migrations.AddField(
            model_name='position',
            name='order_id_in',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='position_in', to='main.order'),
        ),
        migrations.AddField(
            model_name='position',
            name='order_id_out',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='position_out', to='main.order'),
        ),
    ]
