# Generated by Django 3.1 on 2022-02-25 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20220225_1004'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at', 'preorder_id']},
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'ordering': ['-created_at', 'preorder_id']},
        ),
        migrations.AlterModelOptions(
            name='preorder',
            options={'ordering': ['-created_at', 'buyer']},
        ),
        migrations.AlterModelOptions(
            name='requestlog',
            options={'ordering': ['-created_at', 'origin']},
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('Filled', 'Filled'), ('New', 'New'), ('Cancelled', 'Cancelled')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='type',
            field=models.CharField(blank=True, choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=30, null=True),
        ),
    ]
