# Generated by Django 3.1 on 2022-03-04 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20220225_1713'),
    ]

    operations = [
        migrations.RenameField(
            model_name='position',
            old_name='btc_rate_in',
            new_name='btc_price_in',
        ),
        migrations.RenameField(
            model_name='position',
            old_name='btc_rate_out',
            new_name='btc_price_out',
        ),
    ]
