# Generated by Django 3.1 on 2022-03-04 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20220304_1732'),
    ]

    operations = [
        migrations.RenameField(
            model_name='position',
            old_name='order_id_in',
            new_name='order_in',
        ),
        migrations.RenameField(
            model_name='position',
            old_name='order_id_out',
            new_name='order_out',
        ),
    ]
