# Generated by Django 3.1 on 2022-03-05 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20220304_1754'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='preorder_id',
            new_name='preorder',
        ),
        migrations.RenameField(
            model_name='position',
            old_name='preorder_id',
            new_name='preorder',
        ),
        migrations.AlterField(
            model_name='order',
            name='btc_quantity',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True),
        ),
    ]
