# Generated by Django 3.1 on 2022-03-09 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20220305_1404'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RequestLog',
            new_name='HedgeLog',
        ),
    ]
