# Generated by Django 3.1 on 2022-03-09 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20220309_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='hedgelog',
            name='preorder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='main.preorder'),
        ),
    ]
