# Generated by Django 3.1 on 2022-03-21 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20220321_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='sum_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
