# Generated by Django 3.1 on 2022-03-23 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_order_sum_usd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='position',
            old_name='btc_quantity',
            new_name='sum_btc',
        ),
        migrations.RenameField(
            model_name='preorder',
            old_name='finishing_at',
            new_name='finished_at',
        ),
        migrations.AddField(
            model_name='preorder',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='preorder',
            name='order_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='preorder',
            name='product_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='preorder',
            name='size',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
