# Generated by Django 3.1 on 2022-03-23 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20220323_1254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='btc_quantity',
            new_name='sum_btc',
        ),
    ]
